# Generated by Django 5.2.1 on 2025-06-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_recreate_user_table'),
    ]

    operations = [
    ]
