# Generated by Django 5.2.3 on 2025-06-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_fix_project_fields'),
    ]

    operations = [
    ]
